'use client';

import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Download, AlertCircle, CheckCircle2, Droplet, Clock } from 'lucide-react';
import { AreaChart, Area, XAxis, Tooltip, ResponsiveContainer } from 'recharts';
import jsPDF from 'jspdf';

// --- Framer Motion Variants ---
const containerVariants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.1 } }
};

const itemVariants = {
  hidden: { y: 20, opacity: 0 },
  visible: { y: 0, opacity: 1, transition: { type: "spring", stiffness: 100 } }
};

// --- Mock Data ---
const mockHeatmapData = [
  { time: '8 AM', vends: 2 }, { time: '10 AM', vends: 5 }, 
  { time: '12 PM', vends: 15 }, { time: '2 PM', vends: 22 }, 
  { time: '4 PM', vends: 8 }, { time: '6 PM', vends: 12 },
  { time: '8 PM', vends: 4 }
];

const mockLossData = [
  { product: 'Midnight Musk', expected: 450, actual: 445, status: 'Healthy' },
  { product: 'Aqua Surge', expected: 200, actual: 198, status: 'Healthy' },
  { product: 'Ultra Shield', expected: 150, actual: 40, status: 'Critical' },
];

export default function IntelligencePanel() {
  const [isDownloading, setIsDownloading] = useState(false);
  const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "https://final-year-project-f8ym.vercel.app";

  // --- Frontend PDF Generator ---
  const handleDownloadAudit = async () => {
    setIsDownloading(true);
    try {
      // 1. Fetch live data from your clean FastAPI backend
      const response = await fetch(`${API_BASE_URL}/api/admin/analytics`);
      if (!response.ok) throw new Error("Failed to fetch analytics");
      const stats = await response.json();

      // 2. Initialize an A4 PDF document
      const doc = new jsPDF();

      // --- BRANDING & HEADER ---
      doc.setTextColor(226, 149, 149); // Glacia Pink
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.text("VendCare Monthly Performance Audit", 20, 30);

      // Subtitle & Date
      doc.setTextColor(140, 122, 122); // Soft gray
      doc.setFont("helvetica", "italic");
      doc.setFontSize(12);
      const today = new Date().toLocaleDateString();
      doc.text(`Generated by Glacia Labs Infrastructure • ${today}`, 20, 40);

      // Divider Line
      doc.setDrawColor(249, 234, 234); 
      doc.setLineWidth(0.5);
      doc.line(20, 45, 190, 45);

      // --- EXECUTIVE SUMMARY ---
      doc.setTextColor(74, 63, 63); 
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("Executive Summary", 20, 60);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.text(
        "This automated audit verifies the operational integrity and financial throughput of the VendCare IoT ecosystem.", 
        20, 70, { maxWidth: 170 }
      );

      // --- FINANCIAL METRICS ---
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("Financial Metrics", 20, 95);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.text(`Total Revenue Processed: PKR ${stats.total_revenue?.toLocaleString() || 0}`, 25, 105);
      doc.text(`Estimated Operational Profit: PKR ${stats.estimated_profit?.toLocaleString() || 0}`, 25, 115);

      // --- HARDWARE & THROUGHPUT ---
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("Hardware & Throughput Metrics", 20, 135);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.text(`Total Fluid Dispensed: ${stats.total_volume_dispensed || 0} ml`, 25, 145);

      // --- FOOTER ---
      doc.line(20, 270, 190, 270);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(140, 122, 122);
      doc.text("Report automatically compiled from secure MongoDB transaction ledgers.", 20, 280);

      // 3. Trigger the browser to instantly download the file
      doc.save("vendcare-audit.pdf");

    } catch (error) {
      console.error("Failed to generate report:", error);
      alert("Network error. Could not compile the PDF.");
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <motion.div 
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="w-full max-w-6xl mx-auto space-y-8"
    >
      {/* Header */}
      <motion.div variants={itemVariants} className="mb-8">
        <h2 className="text-3xl font-serif italic text-[#4A3F3F]">System Intelligence</h2>
        <p className="text-[#8C7A7A] text-xs font-bold uppercase tracking-[0.2em] mt-1">
          Advanced Analytics & Operations
        </p>
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* --- LEFT COLUMN (Heatmap) --- */}
        <motion.div variants={itemVariants} className="lg:col-span-2 space-y-8">
          <div className="bg-white/60 backdrop-blur-xl border border-white/40 p-8 rounded-[2.5rem] shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
            <div className="flex items-center justify-between mb-8">
              <div>
                <h3 className="text-lg font-bold text-[#4A3F3F]">Predictive Traffic Heatmap</h3>
                <p className="text-xs text-[#8C7A7A]">Optimal restock windows based on peak usage.</p>
              </div>
              <div className="w-10 h-10 rounded-full bg-[#fcf4f4] flex items-center justify-center text-[#E29595]">
                <Clock size={20} />
              </div>
            </div>
            
            <div className="h-64 w-full">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={mockHeatmapData}>
                  <defs>
                    <linearGradient id="colorVends" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#E29595" stopOpacity={0.4}/>
                      <stop offset="95%" stopColor="#E29595" stopOpacity={0}/>
                    </linearGradient>
                  </defs>
                  <XAxis dataKey="time" axisLine={false} tickLine={false} tick={{fill: '#8C7A7A', fontSize: 12}} />
                  <Tooltip 
                    contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 10px 25px rgba(0,0,0,0.05)' }}
                    cursor={{ stroke: '#F3C5C5', strokeWidth: 2, strokeDasharray: '5 5' }}
                  />
                  <Area type="monotone" dataKey="vends" stroke="#E29595" strokeWidth={3} fillOpacity={1} fill="url(#colorVends)" />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </div>
        </motion.div>

        {/* --- RIGHT COLUMN (Audit & Loss Prevention) --- */}
        <motion.div variants={itemVariants} className="space-y-8">
          
          {/* Automated Audit Card */}
          <div className="bg-[#4A3F3F] text-white p-8 rounded-[2.5rem] shadow-xl relative overflow-hidden group">
            {/* Decorative background element */}
            <div className="absolute top-[-50px] right-[-50px] w-32 h-32 bg-[#E29595] rounded-full blur-3xl opacity-20 group-hover:opacity-40 transition-opacity" />
            
            <h3 className="text-lg font-serif italic mb-2 relative z-10">Monthly Performance Audit</h3>
            <p className="text-xs text-white/60 mb-8 relative z-10">Compile hardware throughput and revenue into a professional document.</p>
            
            <button 
              onClick={handleDownloadAudit}
              disabled={isDownloading}
              className="w-full relative z-10 py-4 px-6 bg-white/10 hover:bg-white/20 border border-white/10 rounded-2xl flex items-center justify-center gap-3 transition-all backdrop-blur-md"
            >
              {isDownloading ? (
                <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1, ease: "linear" }}>
                  <Droplet size={18} />
                </motion.div>
              ) : (
                <Download size={18} />
              )}
              <span className="text-sm font-bold uppercase tracking-widest">
                {isDownloading ? 'Compiling...' : 'Generate PDF'}
              </span>
            </button>
          </div>

          {/* Loss Prevention Analytics */}
          <div className="bg-white/60 backdrop-blur-xl border border-white/40 p-8 rounded-[2.5rem] shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
            <h3 className="text-lg font-bold text-[#4A3F3F] mb-6">Loss Prevention</h3>
            
            <div className="space-y-4">
              {mockLossData.map((item, idx) => (
                <div key={idx} className="flex items-center justify-between p-4 rounded-2xl bg-white/50 border border-white/50">
                  <div>
                    <p className="text-sm font-bold text-[#4A3F3F]">{item.product}</p>
                    <p className="text-[10px] text-[#8C7A7A] uppercase tracking-wider">
                      Est. {item.expected}ml | Act. {item.actual}ml
                    </p>
                  </div>
                  <div>
                    {item.status === 'Healthy' ? (
                      <div className="flex items-center gap-1 text-green-500 bg-green-50 px-2 py-1 rounded-lg">
                        <CheckCircle2 size={14} />
                        <span className="text-[10px] font-bold uppercase">Healthy</span>
                      </div>
                    ) : (
                      <div className="flex items-center gap-1 text-red-500 bg-red-50 px-2 py-1 rounded-lg animate-pulse">
                        <AlertCircle size={14} />
                        <span className="text-[10px] font-bold uppercase">Critical</span>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>

        </motion.div>
      </div>
    </motion.div>
  );
}